In [1]:
import numpy as np


In [50]:
import time
#in vectorized case 
a=np.random.rand(1000000)
b=np.random.rand(1000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
print("vectorized version:"+str(1000*(toc-tic))+ "ms")
print(c)
#non-vectorizaes
c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print("non-vectorized version:"+str(1000*(toc-tic)) +"ms")
print(c)

vectorized version:3.9894580841064453ms
250030.0593916918
non-vectorized version:772.3550796508789ms
250030.0593916898


In [1]:
import numpy as np


In [18]:
a=np.random.randn(5)
print(a)
print(a.T)
print(np.dot(a.T,a))

[-0.34187618 -0.48077987 -0.57060096  1.54986859 -0.55888856]
[-0.34187618 -0.48077987 -0.57060096  1.54986859 -0.55888856]
3.388063110381075


In [21]:
b=np.random.randn(5,1)
print(b.shape)
print(b)
print(b.T)
print(np.dot(b.T,b))

(5, 1)
[[ 0.2607503 ]
 [ 0.83316953]
 [-0.66439642]
 [ 0.47406717]
 [-0.72959189]]
[[ 0.2607503   0.83316953 -0.66439642  0.47406717 -0.72959189]]
[[1.96062879]]
